# Generated by Django 2.1.1 on 2018-10-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Обозначение товара')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Изображение товара')),
                ('snippet', models.CharField(blank=True, max_length=128, null=True, verbose_name='Краткое описание товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Полное описание товара')),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Scarf',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
    ]
