# Generated by Django 2.1.1 on 2018-10-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Image', verbose_name='Изображение товара'),
        ),
    ]
