# Generated by Django 2.1.1 on 2018-10-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20181014_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название изображения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='value',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
    ]
